### ISSUE TITLE
Wrong texture path - GlobalConfig.cfg

### ISSUE THREAD

**Issue by davedev** [SpaceODY/PRVE#1]
### Wrong texture path
_/PRVE/Configs/PRVE_Configs/GlobalConfig.cfg_
_/PRVE-64k/Configs/PRVE_Configs/GlobalConfig.cfg_

`value = RSSVE/Textures/DetailTextures/DetailCloudParticle_NRM`

should probably be

`value = PRVE/Textures/DetailTextures/DetailCloudParticle_NRM`

**Comment by SpaceODY** [comment]
I was wondering why the clouds never had a particle texture. Will be fixed in 1.6.

**Comment by davedev** [comment]
It happens.  "Find and replace" in Notepad++ (or similar) is your best friend in such cases. :D

Just want to say - I currently have an RSS/RO/RP-1 instance running on 1.11.2 with PRVE and PRVE-64k, alongside Canaveral-HD.  It is, hands down, the most beautiful rendering of Earth I've ever seen in KSP.  I've been doing an RP-1 career Iivestream on Twitch, and the folks who stop by when I'm in flight are also pleased by it.  The sunrises and sunsets are especially nice.  I'll put together a highlight clip or several and post them - you should see the fantastic results of your work!
