### ISSUE TITLE
Several major config file issues causing ModuleManager Mayhem.  Suggested fixes included.

### ISSUE THREAD

**Issue by davedev** [SpaceODY/PRVE#2]
See attached ModuleManager cache.  I started digging when performance was not what I expected and I saw lots of these in the player.log:

`[Scatterer][Error] Destroying duplicate instance, check your install for duplicate scatterer folders, or nested GameData folders`

Examining the ModuleManager cache led to these two, rather large problems.  I was able to fix both with new MM patches - I will provide my changes in case you'd like to test them for inclusion in 1.6.

**Issue 1** - MM is adding earth's atmo data to every atmo module (caused by MM syntax in PRVE-64k/Earth-Atmosphere.cfg).  

**Issue 2** - Ocean material attribute changes for Kopernicus are duplicating both Kerbin and the Ocean Material attributes instead of editing the existing ones.  (Caused by MM syntax in RSS_Ocean.cfg) .

**Fix for Issue 1**
Replace PRVE-64k/Scatterer_config/Earth_Atmosphere.cfg with this patch:
```
@Scatterer_atmosphere:AFTER[PRVE]
{
	@Atmo[Earth]
	{
		%experimentalAtmoScale = 1.05
	}
}
```

**Fix for issue 2**
Replace /PRVE/Scatterer-Configs/Earth/RSS_Oceans.cfg with this:

```
@Kopernicus:AFTER[RealSolarSystem]
{
	@Body[Kerbin]
	{
		@Ocean[Material]
		{
			%oceanOpacity = 0.85
			%color = 0.495, 0.52, 0.565, 1.0
			%colorFromSpace = 1.117, 0.142, 0.197, 1.0
			%fogColor = 0.918, 0.918, 1.0, 1.0
			%specColor = 1.0, 1.0, 1.0, 1.0
			%shininess = 0.697
		}
	}
}
```

I'm testing the changes more thoroughly right now - so far so good - I'll report back after a couple hours playtime.

**Comment by davedev** [comment]
Issue and fixes confirmed on my end - performance was severely degraded when above atmosphere before the changes - now it is not!    

Might also be worth mentioning, the PRVE/Configs/Scatterer_Configs/ScattererSettings.cfg patch isn't the source of truth for scatterer settings - likely because it contains a :FOR followed by an :AFTER.  MM will only pay attention to the first of any two sorting directives.  

Recommend changing
`@Scatterer_config:FOR[PRVE]:AFTER[scatterer]` 
to
`@Scatterer_config:AFTER[scatterer]:FOR[PRVE]`

I'm assuming you want the :FOR directive there to define PRVE for MM.  I _think_ placing it after another sorting directive will discard it for sorting purposes but, still register the modname as only :FOR can do.  Worst case, it gets ignored completely.  The important thing is the :AFTER gets processed to apply your settings.

*It will still throw a yellow MM warning if there are two sorting directives, which many people don't like to see, even though it's harmless.  Just food for thought.

Didn't open it as a new issue because it's all MM syntax stuff... this topic should suffice 👍

**Comment by davedev** [comment]
With the performance stuff seemingly fixed, I went after the scatterer exceptions and lack of a corona on the sun.

Currently, the Kopernicus.cfg file is also suffering from MM syntax issues.  Lots of & operators where they don't belong.

Edit:  The corona is back on the sun!  Looks great.  I only fixed the sun for now, I can do the other bodies later on.  This has resolved both the missing corona AND the scatterer sunflare and skybox exceptions on every scene change!  Making HUGE progress here.

Here's the relevant part of the patch - it's basically just removing all the & and merging the material stuff into one pass:

```
    @Body[Sun]
    {
        @ScaledVersion
        {
            Light
            {
                %sunlightColor = 1.0, 1.0, 1.0, 1.0
                %sunlightIntensity = 1.0
                %sunlightShadowStrength = 0.9
                %scaledSunlightColor = 1.0, 1.0, 1.0, 1.0
                %scaledSunlightIntensity = 1.0
                %IVASunColor = 1.0, 1.0, 1.0, 1.0
                %IVASunIntensity = 1.0
                %ambientLightColor = 0.1, 0.1, 0.1, 1.0
                %sunLensFlareColor = 0.0, 0.0, 0.0, 0.0
                %sunAU = 149597870700
            }
            Coronas
            {
                %scaleSpeed = 0.01
                %scaleLimitX = 10
                %scaleLimitY = 10
                %updateInterval = 2.5
                %speed = 10
                %rotation = 0
			}	
            Material
            {     
                %texture = PRVE/Textures/MainTextures/Misc/SunCorona
		%emitColor0 = 0.85, 0.85, 0.85, 1.0
                %emitColor1 = 0.975, 0.975, 0.85, 1.0
                %rimColor = 0.975, 0.975, 0.975, 1.0
                %rimBlend = 2.5
                %rimPower = 0.75
                %sunspotColor = 1.0, 1.0, 1.0, 1.0
                %sunspotPower = 2.0
            }
        }
	}
```

**Comment by davedev** [comment]
If you upload the file structure to a branch instead of just a packaged release, I could open pull requests and you could merge them.  Best way to keep track of a not un-complex system of MM patches, IMHO.  Just a suggestion.

**Comment by davedev** [comment]
Some screenshots with all the above fixes in place:
![image](https://user-images.githubusercontent.com/4571729/158691867-ba27de3a-c56c-455a-a955-13c523cdc265.png)
![image](https://user-images.githubusercontent.com/4571729/158691984-18d7f42c-8fa0-45ba-b341-7b081ba293a0.png)
![image](https://user-images.githubusercontent.com/4571729/158692110-e04a35b6-3a7b-43cc-baef-dcffb874ad4e.png)

**Comment by davedev** [comment]
Spoke too soon on the scatterer exceptions.  Skybox one has still not reappeared, though.  Also, things looking a little janky at certain altitudes - the fixes so far could be both fixing and breaking things.  Need to examine every patch file now to bring everything in line.  I'll work on it this week.

**Comment by SpaceODY** [comment]
Alright, sound good! Thanks for the patches and help for performance and optimization.
