### ISSUE TITLE
Implement Cubemap Cloud Shadows

### ISSUE THREAD

**Issue by ballisticfox** [SpaceODY/PRVE#4]
Since EVE doesn't support cloud on cloud shadows you can fake this by having another cloud layer underneath, can look wonky in some situations.
Config below

OBJECT
	{
		name = MainCloudsShadow
		body = Earth
		altitude = 100
		detailSpeed = 0,5.992569,0		//Important, assumes this layer height is 100 and the original layer height is 8000
		speed = 0,29.962847,0		//Important, derived from (2pi(r+h₁))/x=(2pi(r+h₂))/s
		settings
		{
			_DetailScale = 7.5
			_DetailDist = 0.00000007
			_DistFadeVert = 0.000125
			_UVNoiseAnimation = 0.002,0.002
			_UVNoiseStrength = 0.0006
			_UVNoiseScale = 0.1
			_DistFade = 0.00125
			_Color = 0,0,0,455
			_MainTex
			{
				value = EarthClouds
				type = AlphaCubeMap
				alphaMask = ALPHAMAP_G
			}
			_DetailTex
			{
				value = PRVE/Textures/DetailTextures/EarthCloudsNew/detailMed
			}
			_UVNoiseTex
			{
				value = PRVE/Textures/DetailTextures/DetailUVNoise
			}
		}
		layer2D
		{
			macroCloudMaterial
			{
				_RimDist = 0.0001
				_InvFade = 0.0004
			}
		}
	}

**Comment by ballisticfox** [comment]
[CloudShadows.txt](https://github.com/SpaceODY/PRVE/files/8790060/CloudShadows.txt)

**Comment by SpaceODY** [comment]
I'll include it in the next release and see how it goes!
